// User
export const USER_LOGIN               = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS       = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR         = 'USER_LOGIN_ERROR'
export const USER_LOGOUT_SUCCESS      = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_ERROR        = 'USER_LOGOUT_ERROR'
export const USER_REGISTER            = 'USER_REGISTER'
export const USER_REGISTER_SUCCESS    = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR      = 'USER_REGISTER_ERROR'
export const CHECK_USER_DATA          = 'CHECK_USER_DATA'
export const USER_DATA                = 'USER_DATA'

export const FETCH_USERDATA_REQUEST   = 'FETCH_USERDATA_REQUEST'
export const FETCH_USERDATA_SUCCESS   = 'FETCH_USERDATA_SUCCESS'
export const FETCH_USERDATA_FAILURE   = 'FETCH_USERDATA_FAILURE'


// Dashboard
export const DATABASE_REQUEST         = 'DATABASE_REQUEST'
export const DATABASE_RECEIVE         = 'DATABASE_RECEIVE'
export const DATABASE_RECEIVE_ERROR   = 'DATABASE_RECEIVE_ERROR'
export const FETCH_PROGRESS_REQUEST   = 'FETCH_PROGRESS_REQUEST'
export const FETCH_PROGRESS_SUCCESS   = 'FETCH_PROGRESS_SUCCESS'
export const FETCH_PROGRESS_FAILURE   = 'FETCH_PROGRESS_FAILURE'
export const UPDATE_PROGRESS_REQUEST  = 'UPDATE_PROGRESS_REQUEST'
export const UPDATE_PROGRESS_SUCCESS  = 'UPDATE_PROGRESS_SUCCESS'
export const UPDATE_PROGRESS_FAILURE  = 'UPDATE_PROGRESS_FAILURE'

// Settings
export const CHARACTER_SEARCH         = 'CHARACTER_SEARCH'
export const CHARACTER_RESULTS        = 'CHARACTER_RESULTS'
export const CHARACTER_RESULTS_ERROR  = 'CHARACTER_RESULTS_ERROR'
export const CHARACTER_SELECT         = 'CHARACTER_SELECT'
export const CHARACTER_SELECT_ERROR   = 'CHARACTER_SELECT_ERROR'
export const CHARACTER_AUTH_CHECK     = 'CHARACTER_AUTH_CHECK'
export const CHARACTER_VERIFIED       = 'CHARACTER_VERIFIED'
