// User
export const USER_LOGIN_SUCCESS     = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR       = 'USER_LOGIN_ERROR'
export const USER_LOGOUT_SUCCESS    = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_ERROR      = 'USER_LOGOUT_ERROR'
export const USER_REGISTER_SUCCESS  = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR    = 'USER_REGISTER_ERROR'
export const CHECK_USER_DATA        = 'CHECK_USER_DATA'


// Dashboard
export const DATABASE_REQUEST       = 'DATABASE_REQUEST'
export const DATABASE_RECEIVE       = 'DATABASE_RECEIVE'
export const DATABASE_RECEIVE_ERROR = 'DATABASE_RECEIVE_ERROR'
// const TRACKING_UPDATE = 'TRACKING_UPDATE'
